### ISSUE TITLE
Any way to also get "off market" homes?

### ISSUE THREAD

**Issue by joshbowyer** [johnbalvin/pyzill#10]
If you search in Zillow for a house address that is not listed as sale/rent/sold you will get a page with info. Is there a filter that can be used to also pull those in by lat/lon?

**Comment by johnbalvin** [comment]
no, in order to know if it was sold you first need to save all the results in a database, then iterate over all this results each day and check if the property still available

**Comment by joshbowyer** [comment]
So for properties that have never been listed on Zillow they are not accessible aside from searching the address manually?

**Comment by johnbalvin** [comment]
if you would have to do it manually on the page, how would that look like?

**Comment by joshbowyer** [comment]
You have to search for an address (or zoom way in and click the dollar value bubble on the house) which brings up its listing. However the status is Off Market and the tooltip says "This home is not currently listed for sale or rent on Zillow."

It doesnt appear in searches as searches seem to require a status of For Sale, For Rent, or Sold

**Comment by johnbalvin** [comment]
you are right, but it looks like it does return the properties off the market , you can try with any rent, sold or for sale, you will still get the off market properties
![image](https://github.com/user-attachments/assets/7b6fc135-c1fc-49f5-842e-ee8a11fa6292)
