### ISSUE TITLE
Searching with coordinates gets blocked - Error 403

### ISSUE THREAD

**Issue by Merci93** [johnbalvin/pyzill#2]
Searching with coordinates seems to get blocked at some point. Probably an IP address blocking or something since this calls the backend API. Throws an Error 403 and stops working. Any way this can be remedied?

**Comment by Merci93** [comment]
Figured it out.

Zillow aside having an anti-bot scraper, implemented rate limiting on their end. Too much requests per second gets flagged as bot and the IP get's temporarilly blocked. Adding a random generator for sleep time between each requests solved this.

**Comment by johnbalvin** [comment]
Hi, yes it seems to the IP, thats why you should use proxies

**Comment by asrihari** [comment]
Hi John, Thank you for publishing this code. I started using this functionality last week to pull for-sale data in my area. It was working fine for few days but then started giving below error. I tried with proxies but no dice. Trying to understand if it's just me or zillow did something on their end to prevent these calls. Any insights into are greatly appreciated.

Traceback (most recent call last):
  File "C:\Zillow\TestPyZill.py", line 13, in <module>
    results_sold = pyzill.sold(pagination, ne_lat,ne_long,sw_lat,sw_long,zoom_value, "")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyzill\search.py", line 120, in sold
    return search(pagination,ne_lat,ne_long,sw_lat,sw_long,zoom_value,rent,proxy_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyzill\search.py", line 194, in search
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
