### ISSUE TITLE
Error while using the search functionality

### ISSUE THREAD

**Issue by asrihari** [johnbalvin/pyzill#3]
Hi John, Thank you for publishing this code. I started using this functionality last week to pull for-sale data in my area. It was working fine for few days but then started giving below error. I tried with proxies but no dice. Trying to understand if it's just me or zillow did something on their end to prevent these calls. Any insights into are greatly appreciated.

Traceback (most recent call last):
File "C:\Zillow\TestPyZill.py", line 13, in
results_sold = pyzill.sold(pagination, ne_lat,ne_long,sw_lat,sw_long,zoom_value, "")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyzill\search.py", line 120, in sold
return search(pagination,ne_lat,ne_long,sw_lat,sw_long,zoom_value,rent,proxy_url)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyzill\search.py", line 194, in search
data = response.json()
^^^^^^^^^^^^^^^
File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 978, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Update: 

It threw an an addition error afterwards. This is with using a proxy server

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.zillow.com', port=443): Max retries exceeded with url: /async-create-search-page-state (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000256C93194F0>: Failed to resolve 'www.zillow.com' ([Errno 11001] getaddrinfo failed)"))

**Comment by johnbalvin** [comment]
It should be fixed by now, sorry for delay, I've been busy at work
