### ISSUE TITLE
Response - 403 during search

### ISSUE THREAD

**Issue by selryn** [johnbalvin/pyzill#4]
Hi John - 

First, thank you for this code.

Second, I'm a little clueless about scraping and good practices for GitHub so keep that in mind.

I was getting a response code of 403 using the search function leading to similar error message as the issue you just closed last week where the response.json call can't parse properly. (May be worth sending some kind of error message for when a request isn't returned properly?) . After some googling, I went in and tested updating the header with the addition: 

'accept-encoding': 'gzip, deflate, br'

That gave me a response code of 200. I haven't yet tried implementing that change within the overall code to then use your test3() function as written to see if it fixed the entire issue. It looks like it still isn't actually returning results but I'm thinking that's on my side. It'll be something to continue poking at in the next few days. Let me know if you have any thoughts!

**Comment by johnbalvin** [comment]
It will be fixed this week

**Comment by johnbalvin** [comment]
I wasn't able to replicate the issue. Could you try using a VPN or a proxy to check if it works?
It's working well on my side. What probably happened is that you were making multiple calls to Zillow's server, and it flagged your IP
