### ISSUE TITLE
More of a request to offer the capability to seach by URL

### ISSUE THREAD

**Issue by RitchZoeSquad** [johnbalvin/pyzill#8]
More of a request to offer the capability to search by URL

**Comment by johnbalvin** [comment]
The issue would be that the response format is not the same for aparments and homes, so the response won't be always the same

**Comment by RitchZoeSquad** [comment]
I meant to be able to pull two different instances running ollama.


I have two pcs and would like to be able to see both pcs models so that I have the capability to make more asynchronous calls.

**Comment by johnbalvin** [comment]
Response from diferent properties return difererent results, apartment, homes, buildings ..etc so creating a function to get the result by just the url wont be good

**Comment by johnbalvin** [comment]
Response from diferent properties return difererent results, apartment, homes, buildings ..etc so creating a function to get the result by just the url wont be good
